level: info
development: false
disableCaller: false
disableStacktrace: false
encoding: console
outputPaths:
  # Full path or relative path
  - stdout
errorOutputPaths:
  - stderr
initialFields: {}
encoderConfig:
  messageKey: msg
  levelKey: level
  timeKey: ts
  nameKey: logger
  callerKey: caller
  stacktraceKey: stacktrace
  lineEnding: "\n"
  levelEncoder: capital
  timeEncoder: iso8601
  durationEncoder: ""
  callerEncoder: short
  nameEncoder: full