---
appName: rk-server
event:
  format: RK
  quiet: false
  outputPaths:
    - stdout
  loggerConf: "example/grpc/configs/query.yaml"
logger:
  - name: app
    quiet: false
    outputPath: stdout
    loggerConf: "example/grpc/configs/app.yaml"
    maxsize: 1
    maxage: 7
    maxbackups: 3
    localtime: true
    compress: true
  - name: query
    quiet: false
    outputPath: stdout
    loggerConf: "example/grpc/configs/query.yaml"
    maxsize: 1
    maxage: 7
    maxbackups: 3
    localtime: true
    compress: true
config:
  - name: rk-main
    path: "example/grpc/configs/rk.yaml"
    format: RK
    global: false
grpc:
  - name: greeter
    port: 1949
    enableCommonService: true
    tls:
      enabled: false
      user:
        enabled: false
        certFile: "example/grpc/server/cert/server.pem"
        keyFile: "example/grpc/server/cert/server-key.pem"
      auto:
        enabled: false
        certOutput: "example/grpc/server/cert"
    gw:
      enabled: true
      port: 8080
      enableTV: true
      sw:
        enabled: true
        path: sw
        jsonPath: "example/grpc/api/v1"
        headers:
          - "cache-control: no-cache"
    loggingInterceptor:
      enabled: true
      enableLogging: true
      enableMetrics: true
      enablePayloadLogging: false
prom:
  enabled: true
  port: 1608
  path: metrics
proto:
  source:
    - api/v1/*.proto
  import:
    - third-party/googleapis
  doc:
    output: docs
    name: rk-server-demo
    type:
      - html
      - markdown
ut:
  output: docs
build:
  goos: darwin
  goarch: amd64
env:
  REALM: rk
  DOMAIN: dev
  REGION: cn-north-pek
  AZ: cn-north-pek-1
