---
appName: rk-server
event:
  format: RK
  quiet: false
logger:
  - name: app
    confPath: "example/gin/configs/zap-app.yaml"
    forBoot: true
  - name: query
    confPath: "example/gin/configs/zap-query.yaml"
    forEvent: true
config:
  - name: rk-main
    path: "example/gin/configs/rk.yaml"
    format: RK
    global: false
gin:
  - name: greeter
    port: 8080
    tls:
      enabled: true
      port: 8443
      user:
        enabled: false
        certFile: "example/gin/server/cert/server.pem"
        keyFile: "example/gin/server/cert/server-key.pem"
      auto:
        enabled: true
        certOutput: "example/gin/server/cert"
    sw:
      enabled: true
      path: "sw"
      jsonPath: "example/gin/server/docs"
      insecure: true
      headers:
        - "cache-control: no-cache"
    enableCommonService: true
    loggingInterceptor:
      enabled: true
      enableLogging: true
      enableMetrics: true
    authInterceptor:
      enabled: false
      realm: "rk"
      credentials:
        - "foo:pass"
        - "bar:pass"
prom:
  enabled: true
  port: 1608
  path: metrics
  pushGateway:
    enabled: false
    remoteAddr: xxx
    intervalMS: 2000
    jobName: xxx
ut:
  output: docs
build:
  goos: darwin
  goarch: amd64
env:
  REALM: rk
  DOMAIN: dev
  REGION: cn-north-pek
  AZ: cn-north-pek-1
