---
application: rk-server
event:
  format: RK
  quiet: false
  outputPaths:
    - stdout
  loggerConf: "example/gin/configs/query.yaml"
logger:
  - name: app
    quiet: false
    outputPath: stdout
    loggerConf: "example/gin/configs/app.yaml"
    maxsize: 1
    maxage: 7
    maxbackups: 3
    localtime: true
    compress: true
config:
  - name: rk-main
    path: "example/gin/configs/app.yaml"
    format: RK
    global: false
env:
  REALM: rk
  DOMAIN: dev
  REGION: cn-north-pek
  AZ: cn-north-pek-1
gin:
  - name: greeter
    port: 8080
    tls:
      enabled: false
      user:
        enabled: false
        certFile: "example/gin/server/cert/server.pem"
        keyFile: "example/gin/server/cert/server-key.pem"
      auto:
        enabled: true
        certOutput: "example/gin/server/cert"
    sw:
      enabled: true
      path: "sw"
      jsonPath: "example/gin/server/docs"
      headers:
        - "cache-control: no-cache"
    enableCommonService: true
    enableTV: true
    loggingInterceptor:
      enabled: true
      enableLogging: true
      enableMetrics: true
    authInterceptor:
      enabled: false
      realm: "rk"
      credentials:
        - "foo:pass"
        - "bar:pass"
prom:
  enabled: true
  port: 1608
  path: metrics
ut:
  output: docs
build:
  goos: darwin
  goarch: amd64
