---
level: info
encoding: console
outputPaths:
  - stdout
errorOutputPaths:
  - stderr
initialFields: {}
encoderConfig:
  messageKey: msg
  levelKey: ''
  nameKey: ''
  timeKey: ''
  callerKey: ''
  stacktraceKey: ''
  callstackKey: ''
  errorKey: ''
  timeEncoder: iso8601
  fileKey: ''
  levelEncoder: capital
  durationEncoder: second
  callerEncoder: full
  nameEncoder: full
maxsize: 1
maxage: 7
maxbackups: 3
localtime: true
compress: true